# Generated by Django 4.2.1 on 2023-05-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestconsultation',
            options={'permissions': (('can_consult', 'Consult Doctor'), ('can deliver', 'can have drugs delivered'))},
        ),
    ]
