# Generated by Django 4.2.1 on 2023-05-20 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sell', '0006_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='remark',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
